---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: default-app
  namespace: argocd
  annotations:
    metadata.weave.works/flamingo-default-app: "https://localhost:8080/applications/argocd/default-app?view=tree"
    link.argocd.argoproj.io/external-link: "http://localhost:9001/kustomize/details?clusterName=Default&name=default-app&namespace=argocd"
spec:
  timeout: 2m
  path: ./demo/artifacts/default-app
  interval: 5m
  prune: true
  force: false
  sourceRef:
    kind: OCIRepository
    name: fsa-demo
    namespace: flux-system
  dependsOn:
  - name: fsa-installation
